package packet;

/**
 *  Available commands enumeration
 */
public enum Command {
    FREQUENCY_DEVICE,
    GAIN_DEVICE,
    TYPE_OF_SIGNAL_DEVICE,
    BOTTOM_SENSOR_DEVICE,
    MODE_DEVICE,
    SOUND_DEVICE,
    BACKLIGHT_DEVICE,
    EXT_SENSOR_DEVICE,
    CHECK_DISPLAY_DEVICE,
    CHECK_KEYBOARD_DEVICE,
    CHECK_CONNECTION_DEVICE,
    ERROR_DEVICE,

    FREQUENCY_STAND,
    VOLTAGE_STAND,
    TYPE_OF_SIGNAL_STAND,
    EXT_SENSOR_STAND,
    CHECK_CONNECTION_STAND,
    ERROR_STAND
}
